cmake_minimum_required(VERSION 3.24)
project(audacity_branding_tests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
find_package(Qt6 REQUIRED COMPONENTS Core Gui Test)
add_executable(brandingstore_tests brandingstore_tests.cpp ../brandingstore.cpp ../brandingstore.h ../../personalize/internal/brandingmodel.cpp ../../personalize/internal/brandingmodel.h ../../personalize/au_personalize.qrc)
target_link_libraries(brandingstore_tests PRIVATE Qt6::Core Qt6::Gui Qt6::Test)
target_include_directories(brandingstore_tests PRIVATE .. ../../personalize/internal)
enable_testing()
add_test(NAME brandingstore_tests COMMAND brandingstore_tests)
